name: Newman
'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 5 * * *
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Newman
        uses: matt-ball/newman-action@v1.0.4
        with:
          envVar: '[{ "key": "appKey", "value": "${{ secrets.APP_KEY }}" }, { "key": "partnerId", "value": "${{ secrets.PARTNER_ID }}" }, { "key": "partnerSecret", "value": "${{ secrets.PARTNER_SECRET }}" }, { "key": "customerId", "value": "${{ secrets.CUSTOMER_ID }}" } ]'
          collection: finicity.postman_collection.json
          folder: '[ "All APIs" ]'